import streamlit as st

def render_technology():
    sec1_html = (
        '<div class="glass-card" id="how-it-works">'
        '<div style="display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 1rem; margin-bottom: 1rem;">'
        '<div style="display: flex; align-items: center; gap: 0.8rem;">'
        '<span style="font-size: 2rem;">🔬</span>'
        '<h2 style="margin: 0; color: #aed581; font-size: 1.8rem; font-weight: 800;">5. Core Technology & Architecture</h2>'
        '</div>'
        '<div style="background: rgba(79, 195, 247, 0.15); border: 1px solid #4fc3f7; padding: 4px 14px; border-radius: 16px; color: #4fc3f7; font-weight: 700; font-size: 0.85rem;">'
        '⚡ Animated Data Flow Pipeline'
        '</div>'
        '</div>'
        '<p style="color: #b0bec5; font-size: 1.05rem; margin-bottom: 1.5rem;">'
        'Sending entire gigabyte-scale datasets directly to an LLM context window burns thousands of dollars on redundant tokens. <b>Groot</b> acts as an intelligent pre-filtering brain across 6 optimized architectural stages:'
        '</p>'
        
        '<!-- Animated Architecture Pipeline Diagram -->'
        '<div style="background: rgba(13, 18, 10, 0.8); border: 1px solid rgba(156, 204, 101, 0.3); border-radius: 14px; padding: 1.2rem; margin-bottom: 2rem; position: relative; overflow: hidden;">'
        '<style>'
        '@keyframes pulse-line {'
        '  0% { background-position: -200% 0; }'
        '  100% { background-position: 200% 0; }'
        '}'
        '@keyframes node-glow {'
        '  0%, 100% { box-shadow: 0 0 10px rgba(156, 204, 101, 0.3); }'
        '  50% { box-shadow: 0 0 25px rgba(129, 199, 132, 0.8), 0 0 35px rgba(79, 195, 247, 0.6); }'
        '}'
        '.arch-nodes-grid {'
        '  display: grid;'
        '  grid-template-columns: repeat(5, 1fr);'
        '  gap: 0.8rem;'
        '  align-items: center;'
        '}'
        '.arch-node {'
        '  background: rgba(28, 43, 25, 0.9);'
        '  border: 1px solid rgba(156, 204, 101, 0.4);'
        '  border-radius: 12px;'
        '  padding: 0.8rem 0.5rem;'
        '  text-align: center;'
        '  transition: all 0.3s ease;'
        '  position: relative;'
        '  z-index: 2;'
        '}'
        '.arch-node:hover {'
        '  transform: translateY(-4px);'
        '  border-color: #81c784;'
        '  box-shadow: 0 8px 25px rgba(129, 199, 132, 0.4);'
        '}'
        '.glow-node {'
        '  animation: node-glow 3s infinite ease-in-out;'
        '}'
        '.pipeline-flow-bar {'
        '  height: 4px;'
        '  width: 100%;'
        '  background: linear-gradient(90deg, #2e7d32 0%, #81c784 50%, #4fc3f7 100%);'
        '  background-size: 200% 100%;'
        '  animation: pulse-line 2.5s infinite linear;'
        '  border-radius: 2px;'
        '  margin: 1rem 0;'
        '}'
        '.arch-bottom-labels {'
        '  display: flex;'
        '  justify-content: space-between;'
        '  gap: 0.5rem;'
        '  font-size: 0.75rem;'
        '  color: #b0bec5;'
        '  flex-wrap: wrap;'
        '}'
        '@media (max-width: 768px) {'
        '  .arch-nodes-grid {'
        '    grid-template-columns: repeat(2, 1fr) !important;'
        '  }'
        '  .arch-bottom-labels {'
        '    flex-direction: column !important;'
        '    align-items: center !important;'
        '    text-align: center !important;'
        '    gap: 0.4rem !important;'
        '  }'
        '}'
        '</style>'

        '<div class="arch-nodes-grid">'
        '<div class="arch-node">'
        '<div style="font-size: 1.6rem;">📄</div>'
        '<div style="color: #aed581; font-weight: 700; font-size: 0.8rem; margin-top: 0.3rem;">1. Raw Input</div>'
        '<div style="color: #b0bec5; font-size: 0.7rem;">100 MB+ PDF</div>'
        '</div>'

        '<div class="arch-node">'
        '<div style="font-size: 1.6rem;">✂️</div>'
        '<div style="color: #81c784; font-weight: 700; font-size: 0.8rem; margin-top: 0.3rem;">2. Chunking</div>'
        '<div style="color: #b0bec5; font-size: 0.7rem;">300-word blocks</div>'
        '</div>'

        '<div class="arch-node glow-node">'
        '<div style="font-size: 1.6rem;">🧠</div>'
        '<div style="color: #4fc3f7; font-weight: 700; font-size: 0.8rem; margin-top: 0.3rem;">3. Vector Engine</div>'
        '<div style="color: #b0bec5; font-size: 0.7rem;">FAISS Indexing</div>'
        '</div>'

        '<div class="arch-node">'
        '<div style="font-size: 1.6rem;">🎯</div>'
        '<div style="color: #aed581; font-weight: 700; font-size: 0.8rem; margin-top: 0.3rem;">4. Top K Search</div>'
        '<div style="color: #b0bec5; font-size: 0.7rem;">Sub-ms retrieval</div>'
        '</div>'

        '<div class="arch-node" style="border-color: #9ccc65; background: rgba(46, 125, 50, 0.3);">'
        '<div style="font-size: 1.6rem;">🤖</div>'
        '<div style="color: #9ccc65; font-weight: 800; font-size: 0.8rem; margin-top: 0.3rem;">5. LLM Inference</div>'
        '<div style="color: #aed581; font-weight: 700; font-size: 0.7rem;">50-90% Token Cut</div>'
        '</div>'
        '</div>'

        '<div class="pipeline-flow-bar"></div>'
        '<div class="arch-bottom-labels">'
        '<span>⚡ Raw Heterogeneous Ingestion</span>'
        '<span style="color: #4fc3f7; font-weight: 700;">Groot Intelligent Vector Pre-Filter Engine</span>'
        '<span style="color: #81c784; font-weight: 700;">Sub-100ms LLM Prompt Delivery</span>'
        '</div>'
        '</div>'

        '<div class="tech-grid">'
        '<div class="tech-step"><div class="tech-step-num">1</div><div class="tech-step-content"><h4>Multi-Format Data Parsing</h4><p>Intelligently ingests PDFs, OCR images, Confluence pages, and DB records while preserving layout semantics.</p></div></div>'
        '<div class="tech-step"><div class="tech-step-num">2</div><div class="tech-step-content"><h4>Dynamic Overlapping Chunking</h4><p>Splits raw text into context-aware chunks with configurable overlap to prevent boundary information loss.</p></div></div>'
        '<div class="tech-step"><div class="tech-step-num">3</div><div class="tech-step-content"><h4>High-Dimensional Vector Embedding</h4><p>Converts text chunks into dense mathematical vector representations for fast semantic comparison.</p></div></div>'
        '<div class="tech-step"><div class="tech-step-num">4</div><div class="tech-step-content"><h4>FAISS Vector Search Indexing</h4><p>Indexes embeddings in high-performance FAISS vector databases for sub-millisecond query retrieval.</p></div></div>'
        '<div class="tech-step"><div class="tech-step-num">5</div><div class="tech-step-content"><h4>Top-K Semantic Pre-Filtering</h4><p>Queries prompt against vector database to isolate only the top <i>K</i> highest relevance context chunks.</p></div></div>'
        '<div class="tech-step"><div class="tech-step-num">6</div><div class="tech-step-content"><h4>Ultra-Focused LLM Inference</h4><p>Delivers clean, condensed context to Gemini/LLM — eliminating 50-90%+ redundant tokens and lowering API costs.</p></div></div>'
        '</div></div>'
    )
    st.markdown(sec1_html, unsafe_allow_html=True)
    st.write("<br>", unsafe_allow_html=True)
